python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args "{\"horizon\": 96, \"target_channel\": [-1]}" --model-name "amplifier.Amplifier" --model-hyper-params "{\"SCI\": 0, \"batch_size\": 32, \"hidden_size\": 64, \"horizon\": 96, \"lr\": 0.0001, \"norm\": true, \"seq_len\": 96, \"fusion_method\": \"mlp\"}" --gpus 0 --num-workers 1 --timeout 60000 --save-path "test/Amplifier_7_14_mlp/Exchange/h96"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args "{\"horizon\": 96, \"target_channel\": [-1]}" --model-name "time_series_library.DLinear" --model-hyper-params "{\"d_ff\": 2048, \"d_model\": 512, \"horizon\": 96, \"period_len\": 24, \"norm\": true, \"seq_len\": 96, \"fusion_method\": \"mlp\", \"station_lr\": 0.0001, \"lr\": 0.0001}" --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "test/DLinear_7_14_mlp/Exchange/h96"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args "{\"horizon\": 96, \"target_channel\": [-1]}" --model-name "duet.DUET" --model-hyper-params "{\"CI\": 1, \"batch_size\": 32, \"d_ff\": 512, \"d_model\": 512, \"dropout\": 0.5, \"e_layers\": 1, \"factor\": 3, \"fc_dropout\": 0.1, \"horizon\": 96, \"k\": 1, \"loss\": \"MAE\", \"lr\": 0.0005, \"lradj\": \"type1\", \"n_heads\": 1, \"norm\": true, \"num_epochs\": 100, \"num_experts\": 2, \"patch_len\": 48, \"patience\": 5, \"seq_len\": 96, \"fusion_method\": \"mlp\"}" --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "test/DUET_7_14_mlp/Exchange/h96"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args "{\"horizon\": 96, \"target_channel\": [-1]}" --model-name "time_series_library.PatchTST" --model-hyper-params "{\"d_ff\": 1024, \"d_model\": 512, \"e_layers\": 1, \"factor\": 3, \"horizon\": 96, \"n_headers\": 2, \"norm\": true, \"seq_len\": 96, \"fusion_method\": \"mlp\", \"lr\": 0.0001}" --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "test/PatchTST_7_14_mlp/Exchange/h96"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args "{\"horizon\": 96, \"target_channel\": [-1]}" --model-name "time_series_library.TemporalFusionTransformer1" --model-hyper-params "{\"batch_size\": 32, \"n_heads\": 4, \"dropout\": 0.3, \"e_layers\": 2, \"d_layers\": 1, \"seq_len\": 96, \"label_len\": 48, \"horizon\": 96, \"factor\": 3, \"enc_in\": 8, \"dec_in\": 8, \"c_out\": 8, \"lr\": 0.0001, \"patience\": 3, \"num_epochs\": 10, \"data\": \"Exchange\", \"norm\": true, \"covariate_dim\": 7, \"features\": \"MS\", \"d_model\": 32, \"d_ff\": 128}" --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "test/TFT_7_17_new/Exchange/h96"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args "{\"horizon\": 96, \"target_channel\": [-1]}" --model-name "time_series_library.TiDE1" --model-hyper-params "{\"batch_size\": 512, \"d_ff\": 256, \"d_model\": 256, \"horizon\": 96, \"dropout\": 0.1, \"seq_len\": 96, \"e_layers\": 1, \"d_layers\": 2, \"lr\": 0.1, \"patience\": 5, \"num_epochs\": 10, \"c_out\": 9, \"norm\": true, \"covariate_dim\": 7}" --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "test/newTiDE1_7_17/Exchange/h96"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args "{\"horizon\": 96, \"target_channel\": [-1]}" --model-name "timekan.TimeKAN" --model-hyper-params "{\"batch_size\": 32, \"begin_order\": 0, \"d_ff\": 32, \"d_model\": 16, \"down_sampling_layer\": 1, \"down_sampling_window\": 2, \"e_layers\": 2, \"horizon\": 96, \"lr\": 0.01, \"norm\": true, \"num_epochs\": 10, \"patience\": 10, \"seq_len\": 96, \"fusion_method\": \"mlp\"}" --gpus 0 --num-workers 1 --timeout 60000 --save-path "test/TimeKAN_7_14_mlp/Exchange/h96"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args "{\"horizon\": 96, \"target_channel\": [-1]}" --model-name "xpatch.xPatch" --model-hyper-params "{\"batch_size\": 128, \"lr\": 0.001, \"num_epochs\": 20, \"patience\": 5, \"horizon\": 96, \"norm\": true, \"seq_len\": 96, \"fusion_method\": \"mlp\"}" --gpus 0 --num-workers 1 --timeout 60000 --save-path "test/xPatch_7_14_mlp/Exchange/h96"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args "{\"horizon\": 96, \"target_channel\": [-1]}" --model-name "time_series_library.CrossLinear" --model-hyper-params "{\"batch_size\": 16, \"d_ff\": 1024, \"d_model\": 256, \"horizon\": 96, \"norm\": true, \"seq_len\": 96, \"patch_len\": 8, \"alpha\": 1, \"beta\": 0.5, \"lr\": 0.0001, \"patience\": 3, \"num_epochs\": 10, \"mlp_hidden_dims\": 64, \"fusion_method\": \"mlp\"}" --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "test/CrossLinear_mlp_7_16/Exchange/h96"


